package designfiles;

import audio.AudioTone;
import clientproject.*;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import rising.tide.messenger.RisingTideMessenger;

public class Login extends javax.swing.JFrame {

    int xMouse, yMouse;
    Timer timer;

    public Login() {
        initComponents();
        timer = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loginProcess();
            }
        });
        passwordField.setEchoChar((char) 0);
        RisingTideMessenger.defaultIconCreator(Login.this, "Login"); // setting default icon
        
        usernameTitleLabel.setVisible(false);
        passwordTitleLabel.setVisible(false);
    }

    //added by shaafi(18-7-16) the function will handle the login process
    private void loginProcess() {

        timer.stop();
        String password = new String(passwordField.getPassword());
        String username = userNameTextField.getText().toLowerCase();
        if (!username.equalsIgnoreCase("") && !password.equalsIgnoreCase("")) {
            boolean check = ClientProject.loginClient(username, password);
            if (check) {

                OnlineChatUsersListWindow onlineChatUsersListWindow = new OnlineChatUsersListWindow();
                onlineChatUsersListWindow.setVisible(true);
                onlineChatUsersListWindow.setTitle("Rising Tide Messenger");
                onlineChatUsersListWindow.setUserNameLabel(ClientInfo.clientInfoObject.getUserName());
                onlineChatUsersListWindow.setUserImage(ClientInfo.getUserImageBuffer());
                ClientInfo.loginInstance.dispose();
                AudioTone sn = new AudioTone();
                sn.loginSound();
                this.dispose();

            } else {

                login_label.setIcon(new ImageIcon(getClass().getResource("/img/login_logo.png")));
            }
        } else if (password.equalsIgnoreCase("")) {
            login_label.setIcon(new ImageIcon(getClass().getResource("/img/login_logo.png")));
            JOptionPane.showMessageDialog(null, "Enter Your Password Please!");
        } else {
            login_label.setIcon(new ImageIcon(getClass().getResource("/img/login_logo.png")));
            JOptionPane.showMessageDialog(null, "Enter Your User Name Please!");

        }

    }

    //this function changes the login label icon to a loading gif
    public void changeLoginIcon() {
        this.login_label.setIcon(new ImageIcon(getClass().getResource("/img/login_loading.gif")));
        repaint();

        String password = new String(passwordField.getPassword());
        String username = userNameTextField.getText().toLowerCase();

        if (username.equalsIgnoreCase("") && password.equalsIgnoreCase("")) {
            login_label.setIcon(new ImageIcon(getClass().getResource("/img/login_logo.png")));
            JOptionPane.showMessageDialog(null, "Enter Your User Name & Password Please!");
        } else {
            timer.start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTitleLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordTitleLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        aboutUs_label = new javax.swing.JLabel();
        login_label = new javax.swing.JLabel();
        signup_label = new javax.swing.JLabel();
        minimize_button = new javax.swing.JLabel();
        close_button = new javax.swing.JLabel();
        toolbar = new javax.swing.JLabel();
        title_icon_lebel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(10, 10, 65, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 51, 51));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(730, 615));
        setName(""); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTitleLabel.setBackground(new java.awt.Color(204, 204, 204));
        usernameTitleLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        usernameTitleLabel.setForeground(new java.awt.Color(204, 204, 204));
        usernameTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameTitleLabel.setText("USERNAME");
        getContentPane().add(usernameTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 190, 30));

        userNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        userNameTextField.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        userNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userNameTextField.setText("USERNAME");
        userNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTextFieldFocusGained(evt);
            }
        });
        userNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameTextFieldMouseClicked(evt);
            }
        });
        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });
        userNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameTextFieldKeyPressed(evt);
            }
        });
        getContentPane().add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 322, 50));

        passwordTitleLabel.setBackground(new java.awt.Color(204, 204, 204));
        passwordTitleLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        passwordTitleLabel.setForeground(new java.awt.Color(204, 204, 204));
        passwordTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordTitleLabel.setText("PASSWORD");
        getContentPane().add(passwordTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 200, 30));

        passwordField.setBackground(new java.awt.Color(204, 204, 204));
        passwordField.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setText("PASSWORD");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
        });
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 322, 52));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Don't Have An Account ?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, 27));

        aboutUs_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutUs_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoABoutUs.png"))); // NOI18N
        aboutUs_label.setToolTipText("About Us");
        aboutUs_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutUs_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutUs_labelMouseClicked(evt);
            }
        });
        getContentPane().add(aboutUs_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, -1, -1));

        login_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login_logo.png"))); // NOI18N
        login_label.setToolTipText("Login");
        login_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_label.setFocusTraversalPolicyProvider(true);
        login_label.setMaximumSize(new java.awt.Dimension(200, 65));
        login_label.setMinimumSize(new java.awt.Dimension(200, 65));
        login_label.setPreferredSize(new java.awt.Dimension(200, 65));
        login_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_labelMouseClicked(evt);
            }
        });
        getContentPane().add(login_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        signup_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sign_logo.png"))); // NOI18N
        signup_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup_label.setFocusTraversalPolicyProvider(true);
        signup_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_labelMouseClicked(evt);
            }
        });
        getContentPane().add(signup_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, 61));

        minimize_button.setToolTipText("Minimize");
        minimize_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(minimize_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 15, 35, 35));

        close_button.setToolTipText("Close");
        close_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 15, 35, 35));

        toolbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toolbarMouseDragged(evt);
            }
        });
        toolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolbarMousePressed(evt);
            }
        });
        getContentPane().add(toolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 100));

        title_icon_lebel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chat_bg.png"))); // NOI18N
        getContentPane().add(title_icon_lebel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signup_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_labelMouseClicked
        // TODO add your handling code here:
        new SignUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signup_labelMouseClicked

    private void login_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_labelMouseClicked
        // TODO add your handling code here:

        changeLoginIcon();
    }//GEN-LAST:event_login_labelMouseClicked

    private void aboutUs_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUs_labelMouseClicked
        // TODO add your handling code here:
        new AboutUs().setVisible(true);
    }//GEN-LAST:event_aboutUs_labelMouseClicked

    //added by shaafi(18-7-16) to press enter to process login
    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            changeLoginIcon();

        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            JOptionPane.showMessageDialog(null, "There is Space in the password please type again!");
            passwordField.setText("PASSWORD");
            passwordField.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    private void close_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_buttonMouseClicked
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_close_buttonMouseClicked

    private void minimize_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_buttonMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimize_buttonMouseClicked

    private void toolbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMousePressed
        // TODO add your handling code here:

        //getting the x and y position of the mouse when the mouse is pressed 
        //so that we can place the gui in proper position later
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_toolbarMousePressed

    private void toolbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMouseDragged
        // TODO add your handling code here:

        //getting the x and y possition where the mouse is at that moment and set the 
        //jFrame to that place
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_toolbarMouseDragged

    private void userNameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameTextFieldMouseClicked
        if (userNameTextField.getText().equalsIgnoreCase("USERNAME")) {
            userNameTextField.setText("");
            usernameTitleLabel.setVisible(true);
            passwordTitleLabel.setVisible(false);
        }
        if (new String(passwordField.getPassword()).equalsIgnoreCase("")) {
            passwordField.setText("PASSWORD");
            passwordField.setEchoChar((char) 0);
            passwordTitleLabel.setVisible(false);
        }
    }//GEN-LAST:event_userNameTextFieldMouseClicked

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        if (new String(passwordField.getPassword()).equalsIgnoreCase("PASSWORD")) {
            passwordField.setText("");
            passwordField.setEchoChar('*');
            passwordTitleLabel.setVisible(true);
        }

        if (userNameTextField.getText().equalsIgnoreCase("")) {
            userNameTextField.setText("USERNAME");
            usernameTitleLabel.setVisible(false);
        }
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void userNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            JOptionPane.showMessageDialog(null, "There is Space in the username please type again!");
            userNameTextField.setText("USERNAME");
        } 
        
    }//GEN-LAST:event_userNameTextFieldKeyPressed

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        // TODO add your handling code here:
        if (new String(passwordField.getPassword()).equalsIgnoreCase("PASSWORD")) {
            passwordField.setText("");
            passwordField.setEchoChar('*');
            passwordTitleLabel.setVisible(true);

        }

        if (userNameTextField.getText().equalsIgnoreCase("")) {
            userNameTextField.setText("USERNAME");
            usernameTitleLabel.setVisible(false);
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    private void userNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTextFieldFocusGained
        // TODO add your handling code here:
        if (userNameTextField.getText().equalsIgnoreCase("USERNAME")) {
            userNameTextField.setText("");
            usernameTitleLabel.setVisible(true);
        }
        if (new String(passwordField.getPassword()).equalsIgnoreCase("")) {
            passwordField.setText("PASSWORD");
            passwordField.setEchoChar((char) 0);
            passwordTitleLabel.setVisible(false);
            
        }
    }//GEN-LAST:event_userNameTextFieldFocusGained

    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutUs_label;
    private javax.swing.JLabel close_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel login_label;
    private javax.swing.JLabel minimize_button;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordTitleLabel;
    private javax.swing.JLabel signup_label;
    private javax.swing.JLabel title_icon_lebel;
    private javax.swing.JLabel toolbar;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel usernameTitleLabel;
    // End of variables declaration//GEN-END:variables

}
